version: '3'
services:
  db:
    image: 'mongo:latest'
    container_name: 'atascados-db'
    restart: always
    platform: linux/x86_64
    env_file: 
      - .env.development
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - db:/data/db
    network_mode: host
  backend: 
    image: 'atascados-api'
    container_name: 'atascados-api'
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: '.docker/Dockerfile'
    ports:
      - 3000:3000
    env_file:
      - .env.development
    volumes:
      - ./:/app
    network_mode: host
  auth: 
    image: 'atascados-auth'
    container_name: 'atascados-auth'
    platform: linux/x86_64
    build:
      context: .
      dockerfile: '.docker/services/auth/Dockerfile'
    env_file:
      - .env.development
    volumes:
      - ./:/app
    network_mode: host
  back-office: 
    image: 'atascados-back-office'
    container_name: 'atascados-back-office'
    platform: linux/x86_64
    build:
      context: .
      dockerfile: '.docker/services/back-office/Dockerfile'
    env_file:
      - .env.development
    volumes:
      - ./:/app
    network_mode: host  
volumes:
  db:
    driver: local
